package com.aliCheikh.stock.application.dto;

public enum StockReceiptImportIssueCode {
    MISSING_REFERENCE,
    REFERENCE_TOO_LONG,
    DUPLICATE_REFERENCE_IN_FILE,
    MISSING_NAME,
    NAME_TOO_LONG,
    DUPLICATE_NAME_IN_FILE,
    PRODUCT_NAME_ALREADY_USED,
    INACTIVE_PRODUCT,
    MISSING_CATEGORY,
    UNKNOWN_CATEGORY,
    INVALID_UNIT_PRICE,
    NEGATIVE_THRESHOLD,
    INVALID_THRESHOLD,
    INVALID_QUANTITY,
    NEGATIVE_QUANTITY,
    MISSING_QUANTITY,
    MISSING_LOCATION,
    EXECUTION_FAILED
}
