package com.aliCheikh.stock.application.usecase;

import com.aliCheikh.stock.application.dto.ReceiveStockCommand;
import com.aliCheikh.stock.application.dto.TargetLocation;
import com.aliCheikh.stock.application.port.EventPublisher;
import com.aliCheikh.stock.domain.event.DomainEvent;
import com.aliCheikh.stock.domain.event.StockReceived;
import com.aliCheikh.stock.domain.event.StockReplenished;
import com.aliCheikh.stock.domain.model.category.CategoryId;
import com.aliCheikh.stock.domain.model.movement.StockMovement;
import com.aliCheikh.stock.domain.model.movement.port.StockMovementRepository;
import com.aliCheikh.stock.domain.model.product.Product;
import com.aliCheikh.stock.domain.model.product.ProductId;
import com.aliCheikh.stock.domain.model.product.port.ProductRepository;
import com.aliCheikh.stock.domain.model.shared.Money;
import com.aliCheikh.stock.domain.model.shop.ShopId;
import com.aliCheikh.stock.domain.model.stock.LocationId;
import com.aliCheikh.stock.domain.model.stock.StorageLocation;
import com.aliCheikh.stock.domain.model.stock.ports.StorageLocationRepository;
import com.aliCheikh.stock.domain.model.user.UserId;
import com.aliCheikh.stock.domain.service.ReceivingService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.math.BigDecimal;
import java.util.Currency;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

public class ReceiveStockUseCaseTest {

    private ProductRepository productRepository;
    private ReceivingService receivingService;
    private StockMovementRepository stockMovementRepository;
    private StorageLocationRepository storageLocationRepository; // NEW
    private EventPublisher eventPublisher;

    private ReceiveStockUseCase receiveStockUseCase;

    @BeforeEach
    public void setUp() {
        productRepository = mock(ProductRepository.class);
        receivingService = mock(ReceivingService.class);
        stockMovementRepository = mock(StockMovementRepository.class);
        storageLocationRepository = mock(StorageLocationRepository.class); // NEW
        eventPublisher = mock(EventPublisher.class);

        receiveStockUseCase = new ReceiveStockUseCase(
                productRepository, receivingService, stockMovementRepository, storageLocationRepository, eventPublisher
        );
    }

    @Test
    public void should_orchestrate_stock_reception_and_publish_events() {
        // GIVEN
        ProductId productId = ProductId.generate();
        UserId userId = UserId.generate();
        LocationId shopFloorId = LocationId.generate();
        LocationId backStockId = LocationId.generate();
        String productReference = "REF-123";
        ShopId shopId = ShopId.generate();

        ReceiveStockCommand command = new ReceiveStockCommand(
                productReference,
                null, // No product creation for this base test
                shopId,
                userId,
                List.of(
                        new TargetLocation(shopFloorId, 15),
                        new TargetLocation(backStockId, 35)
                )
        );

        // A product with a global alert threshold of 40
        Product product = new Product(productId, "Oil Filter", productReference, CategoryId.generate(), 40, Money.create(BigDecimal.TEN, Currency.getInstance("EUR")));

        // Movements generated by ReceivingService
        List<StockMovement> expectedMovements = List.of(
                mock(StockMovement.class), mock(StockMovement.class)
        );

        // Mock Product lookup
        when(productRepository.findByReference(productReference)).thenReturn(Optional.of(product));
        when(receivingService.receive(anyList(), eq(userId))).thenReturn(expectedMovements);

        // Mock StorageLocations to simulate actual global stock calculation (15 + 35 = 50 > 40 threshold)
        StorageLocation mockedShopFloor = mock(StorageLocation.class);
        when(mockedShopFloor.getStockLevel(productId)).thenReturn(15);

        StorageLocation mockedBackStock = mock(StorageLocation.class);
        when(mockedBackStock.getStockLevel(productId)).thenReturn(35);

        when(storageLocationRepository.findByShopId(shopId)).thenReturn(List.of(mockedShopFloor, mockedBackStock));

        // WHEN
        receiveStockUseCase.execute(command);

        // THEN
        // 1. Verify movements were saved
        verify(stockMovementRepository, times(1)).saveAll(expectedMovements);

        // 2. Capture and verify published events
        @SuppressWarnings("unchecked")
        ArgumentCaptor<List<DomainEvent>> eventCaptor = ArgumentCaptor.forClass(List.class);
        verify(eventPublisher, times(1)).publish(eventCaptor.capture());

        List<DomainEvent> publishedEvents = eventCaptor.getValue();
        assertThat(publishedEvents).hasSize(2);

        // --- Verify First Event (StockReceived) ---
        DomainEvent firstEvent = publishedEvents.get(0);
        assertThat(firstEvent).isInstanceOf(StockReceived.class);
        StockReceived receivedEvent = (StockReceived) firstEvent;

        assertThat(receivedEvent.productId()).isEqualTo(productId);
        assertThat(receivedEvent.totalQuantityReceived()).isEqualTo(50); // 15 + 35
        assertThat(receivedEvent.receivedBy()).isEqualTo(userId);
        assertThat(receivedEvent.locationBreakdown())
                .containsEntry(shopFloorId, 15)
                .containsEntry(backStockId, 35);

        // --- Verify Second Event (StockReplenished) ---
        DomainEvent secondEvent = publishedEvents.get(1);
        assertThat(secondEvent).isInstanceOf(StockReplenished.class);
        StockReplenished replenishedEvent = (StockReplenished) secondEvent;

        assertThat(replenishedEvent.productId()).isEqualTo(productId);
        assertThat(replenishedEvent.productName()).isEqualTo("Oil Filter");
        assertThat(replenishedEvent.globalQuantity()).isEqualTo(50); // Actual stock from mocked repositories
        assertThat(replenishedEvent.threshold()).isEqualTo(40);
    }

}