site:
  title: Auto Stock Management
  start_page: stock-management::index.adoc # Module and start page
content:
  sources:
    - url: . # Local documentation source
      branches: HEAD
      start_path: . # Documentation root
asciidoc:
  extensions:
    - asciidoctor-kroki # Diagram extension
  attributes:
    kroki-server-url: https://kroki.io # External diagram rendering service
    kroki-fetch-diagram: true
    icons: font
    sectnums: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./build/site # Generated site output